### PR TITLE
[TASK] Get the composer's home directory from a command line instead …

### LINKED ISSUE #3: package generation failure
`composer run-script extension-release`
Does everything fine. However it fails at the end.

`Updating dependencies (including require-dev)
Package operations: 11 installs, 0 updates, 0 removals
  - Installing ezyang/htmlpurifier (v4.13.0): Downloading (100%)         
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-factory (1.0.1): Downloading (100%)         
  - Installing psr/http-client (1.0.1): Loading from cache
  - Installing psr/simple-cache (1.0.1): Downloading (100%)         
  - Installing markbaker/matrix (2.1.2): Downloading (100%)         
  - Installing markbaker/complex (2.0.0): Downloading (100%)         
  - Installing myclabs/php-enum (1.8.0): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.22.1): Loading from cache
  - Installing maennchen/zipstream-php (2.1.0): Downloading (100%)         
  - Installing phpoffice/phpspreadsheet (1.17.1): Downloading (100%)         
phpoffice/phpspreadsheet suggests installing mpdf/mpdf (Option for rendering PDF with PDF Writer)
phpoffice/phpspreadsheet suggests installing dompdf/dompdf (Option for rendering PDF with PDF Writer (doesn't yet support PHP8))
phpoffice/phpspreadsheet suggests installing tecnickcom/tcpdf (Option for rendering PDF with PDF Writer (doesn't yet support PHP8))
phpoffice/phpspreadsheet suggests installing jpgraph/jpgraph (Option for rendering charts, or including charts with PDF or HTML Writers)
Writing lock file
Generating autoload files
Generated optimized autoload files (authoritative) containing 573 classes
> [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $HOME/.composer/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar
sh: /home/franz/.composer/vendor/bin/phar-composer: No such file or directory
Script [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $HOME/.composer/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar handling the extension-create-libs event returned with error code 127
Script @extension-create-libs was called via extension-build
Script @extension-build was called via extension-release
[franz@localhost base_excel]$ which composer
/usr/local/bin/composer
`

### PR DESCRIPTION
**Pull request by cjanody**
…of using a hardcoded path

resolve #3

### CODE REVIEW

**Comment by cjanody** [comment]
@franzholz Does it work for you?

**Comment by franzholz** [comment]
I get this result:

    [franz@localhost base_excel]$ composer run-script extension-release
    > mkdir -p Libraries/temp
    > [ -f $(composer config --global home)/vendor/bin/phar-composer ] || composer global require clue/phar-composer
    > if [ ! -f Libraries/phpoffice-phpspreadsheet.phar ]; then cd Libraries/temp && composer require phpoffice/phpspreadsheet=^1.17 && composer config classmap-authoritative true && composer config prepend-autoloader false && composer dump-autoload; fi
    ./composer.json has been updated
    Running composer update phpoffice/phpspreadsheet
    Loading composer repositories with package information
    Updating dependencies
    Nothing to modify in lock file
    Installing dependencies from lock file (including require-dev)
    Nothing to install, update or remove
    Generating optimized autoload files
    Generating optimized autoload files (authoritative)
    Generated optimized autoload files (authoritative) containing 573 classes
    > [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $(composer config --global home)/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar
    Your configuration disabled writing phar files (phar.readonly = On), please update your configuration or run with "php -d phar.readonly=off /home/franz/.config/composer/vendor/bin/phar-composer"
    [1/1] Creating phar Libraries/phpoffice-phpspreadsheet.phar

    In PharComposer.php line 164:
                                                                                                    
    creating archive "Libraries/phpoffice-phpspreadsheet.phar.1790454398.phar" disabled by the p  
    hp.ini setting phar.readonly                                                                  
                                                                                                    

    build [<project> [<target>]]

    Script [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $(composer config --global home)/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar handling the extension-create-libs event returned with error code 1
    Script @extension-create-libs was called via extension-build
    Script @extension-build was called via extension-release


And I have this configuration:

    [root@localhost /]# ls -l /etc/php.d/84_phar.ini 
    -rw-r--r-- 1 root root 150 Apr 27 18:54 /etc/php.d/84_phar.ini
    [root@localhost /]# cat /etc/php.d/84_phar.ini
    extension = phar

    ; http://php.net/phar.readonly
    ;phar.readonly = On

    ; http://php.net/phar.require-hash
    ;phar.require_hash = On

    ;phar.cache_list =

**Comment by franzholz** [comment]
The php documentation says, that `phar.readonly = On` by default.
So I have now modified the php.ini:

    [root@localhost /]# cat /etc/php.d/84_phar.ini
    extension = phar

    ; http://php.net/phar.readonly
    phar.readonly = Off

    ; http://php.net/phar.require-hash
    ;phar.require_hash = On

    ;phar.cache_list =

Now I get it working!

    [franz@localhost base_excel]$ composer run-script extension-release
    > mkdir -p Libraries/temp
    > [ -f $(composer config --global home)/vendor/bin/phar-composer ] || composer global require clue/phar-composer
    > if [ ! -f Libraries/phpoffice-phpspreadsheet.phar ]; then cd Libraries/temp && composer require phpoffice/phpspreadsheet=^1.17 && composer config classmap-authoritative true && composer config prepend-autoloader false && composer dump-autoload; fi
    ./composer.json has been updated
    Running composer update phpoffice/phpspreadsheet
    Loading composer repositories with package information
    Updating dependencies
    Nothing to modify in lock file
    Installing dependencies from lock file (including require-dev)
    Nothing to install, update or remove
    Generating optimized autoload files
    Generating optimized autoload files (authoritative)
    Generated optimized autoload files (authoritative) containing 573 classes
    > [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $(composer config --global home)/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar
    [1/1] Creating phar Libraries/phpoffice-phpspreadsheet.phar
    - Adding main package ""
    - Adding composer base files
    - Adding dependency "ezyang/htmlpurifier" from "vendor/ezyang/htmlpurifier/"
    - Adding dependency "maennchen/zipstream-php" from "vendor/maennchen/zipstream-php/"
    - Adding dependency "markbaker/complex" from "vendor/markbaker/complex/"
    - Adding dependency "markbaker/matrix" from "vendor/markbaker/matrix/"
    - Adding dependency "myclabs/php-enum" from "vendor/myclabs/php-enum/"
    - Adding dependency "phpoffice/phpspreadsheet" from "vendor/phpoffice/phpspreadsheet/"
    - Adding dependency "psr/http-client" from "vendor/psr/http-client/"
    - Adding dependency "psr/http-factory" from "vendor/psr/http-factory/"
    - Adding dependency "psr/http-message" from "vendor/psr/http-message/"
    - Adding dependency "psr/simple-cache" from "vendor/psr/simple-cache/"
    - Adding dependency "symfony/polyfill-mbstring" from "vendor/symfony/polyfill-mbstring/"
    - Setting main/stub
        WARNING: No main bin file defined! Resulting phar will NOT be executable
        Applying chmod 0755

        OK - Creating Libraries/phpoffice-phpspreadsheet.phar (5983.1 KiB) completed after 4.6s
    > chmod -x Libraries/*.phar
    > rm -rf Libraries/temp
    > rm -rf Tests/
    > rm -f .editorconfig
    > rm -f .gitattributes
    > rm -f .gitignore

**Comment by franzholz** [comment]
I give it another try.

    [franz@localhost base_excel (master)]$ composer run-script extension-release
   
     No composer.json in current directory, do you want to use the one at /var/www/html/global-extensions/ext/base_excel? [Y,n]? 
**Y**

     '.Build/Web/typo3conf/ext/base_excel' -> '../../../../.'
     36 packages you are using are looking for funding.
      Use the `composer fund` command to find out more!
    No composer.json in current directory, do you want to use the one at /var/www/html/global-extensions/ext/base_excel? [Y,n]?
**Y**

    No composer.json in current directory, do you want to use the one at /var/www/html/global-extensions/ext/base_excel? [Y,n]?
**Y**

    No composer.json in current directory, do you want to use the one at /var/www/html/global-extensions/ext/base_excel? [Y,n]? 
**Y**

    Generating optimized autoload files (authoritative)
    Generating class alias map file
    > mkdir -p .Build/Web/typo3conf/ext/
    > [ -L .Build/Web/typo3conf/ext/base_excel ] || ln -snvf ../../../../. .Build/Web/typo3conf/ext/base_excel
    Generated optimized autoload files (authoritative) containing 3172 classes
    > [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $(composer config --global home)/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar

    In Packager.php line 207:
                                                                            
    The given path "Libraries/temp/composer.json" is not a readable file  
                                                                            

    build [<project> [<target>]]

    Script [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $(composer config --global home)/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar handling the extension-create-libs event returned with error code 1
    Script @extension-create-libs was called via extension-build
    Script @extension-build was called via extension-release


This error is at the end.

And the "base_excel/public/" must not be there!
It has a path "l/public/typo3/sysext/core/"

TYPO3 core files must not be part of this extension.

"/base_excel/Libraries/temp/" is empty. 
Where are the libraries? Probably the error above made this failing.

**Comment by cjanody** [comment]
Hi,
You should not use the extension's composer.json, you must answer No when asked by composer

**Comment by franzholz** [comment]
That is tricky.

    [franz@localhost base_excel (master)]$ composer run-script extension-release 
    > mkdir -p Libraries/temp
    > [ -f $(composer config --global home)/vendor/bin/phar-composer ] || composer global require clue/phar-composer
    > if [ ! -f Libraries/phpoffice-phpspreadsheet.phar ]; then cd Libraries/temp && composer require phpoffice/phpspreadsheet=^1.17 && composer config classmap-authoritative true && composer config prepend-autoloader false && composer dump-autoload; fi
    No composer.json in current directory, do you want to use the one at /var/www/html/global-extensions/ext/base_excel? [Y,n]? 

**n**

    ./composer.json has been created
    Running composer update phpoffice/phpspreadsheet
    Loading composer repositories with package information
    Updating dependencies
    Lock file operations: 11 installs, 0 updates, 0 removals
    - Locking ezyang/htmlpurifier (v4.13.0)
    - Locking maennchen/zipstream-php (2.1.0)
    - Locking markbaker/complex (2.0.0)
    - Locking markbaker/matrix (2.1.2)
    - Locking myclabs/php-enum (1.8.0)
    - Locking phpoffice/phpspreadsheet (1.17.1)
    - Locking psr/http-client (1.0.1)
    - Locking psr/http-factory (1.0.1)
    - Locking psr/http-message (1.0.1)
    - Locking psr/simple-cache (1.0.1)
    - Locking symfony/polyfill-mbstring (v1.22.1)
    Writing lock file
    Installing dependencies from lock file (including require-dev)
    Package operations: 11 installs, 0 updates, 0 removals
    - Installing myclabs/php-enum (1.8.0): Extracting archive
    - Installing psr/simple-cache (1.0.1): Extracting archive
    - Installing psr/http-message (1.0.1): Extracting archive
    - Installing psr/http-factory (1.0.1): Extracting archive
    - Installing psr/http-client (1.0.1): Extracting archive
    - Installing markbaker/matrix (2.1.2): Extracting archive
    - Installing markbaker/complex (2.0.0): Extracting archive
    - Installing symfony/polyfill-mbstring (v1.22.1): Extracting archive
    - Installing maennchen/zipstream-php (2.1.0): Extracting archive
    - Installing ezyang/htmlpurifier (v4.13.0): Extracting archive
    - Installing phpoffice/phpspreadsheet (1.17.1): Extracting archive
    4 package suggestions were added by new dependencies, use `composer suggest` to see details.
    Generating autoload files
    3 packages you are using are looking for funding.
    Use the `composer fund` command to find out more!
    Generating optimized autoload files (authoritative)
    Generated optimized autoload files (authoritative) containing 573 classes
    > [ -f Libraries/phpoffice-phpspreadsheet.phar ] || $(composer config --global home)/vendor/bin/phar-composer build Libraries/temp/ Libraries/phpoffice-phpspreadsheet.phar
    [1/1] Creating phar Libraries/phpoffice-phpspreadsheet.phar
    - Adding main package ""
    - Adding composer base files
    - Adding dependency "ezyang/htmlpurifier" from "vendor/ezyang/htmlpurifier/"
    - Adding dependency "maennchen/zipstream-php" from "vendor/maennchen/zipstream-php/"
    - Adding dependency "markbaker/complex" from "vendor/markbaker/complex/"
    - Adding dependency "markbaker/matrix" from "vendor/markbaker/matrix/"
    - Adding dependency "myclabs/php-enum" from "vendor/myclabs/php-enum/"
    - Adding dependency "phpoffice/phpspreadsheet" from "vendor/phpoffice/phpspreadsheet/"
    - Adding dependency "psr/http-client" from "vendor/psr/http-client/"
    - Adding dependency "psr/http-factory" from "vendor/psr/http-factory/"
    - Adding dependency "psr/http-message" from "vendor/psr/http-message/"
    - Adding dependency "psr/simple-cache" from "vendor/psr/simple-cache/"
    - Adding dependency "symfony/polyfill-mbstring" from "vendor/symfony/polyfill-mbstring/"
    - Setting main/stub
        WARNING: No main bin file defined! Resulting phar will NOT be executable
        Applying chmod 0755

        OK - Creating Libraries/phpoffice-phpspreadsheet.phar (5988.4 KiB) completed after 0.7s
    > chmod -x Libraries/*.phar
    > rm -rf Libraries/temp
    > rm -rf Tests/
    > rm -f .editorconfig
    > rm -f .gitattributes
    > rm -f .gitignore

**Comment by franzholz** [comment]
[franz@localhost base_excel (master)]$ ls -l Libraries/
    total 5992
    -rw-r--r-- 1 franz franz 6132169 Mai 20 15:05 phpoffice-phpspreadsheet.phar

**Comment by franzholz** [comment]
I only have a file phpoffice-phpspreadsheet.phar. 

I do not get the former class hiearchy:

https://github.com/franzholz/base_excel/tree/v0.1.0/Vendor/PhpSpreadsheet/src/PhpSpreadsheet

**Comment by cjanody** [comment]
It's the only thing you need. https://en.wikipedia.org/wiki/PHAR_(file_format)
The phar file is loaded in the ext_localconf.php file
```php
   // Require 3rd-party libraries, in case TYPO3 does not run in composer mode
    if (!\TYPO3\CMS\Core\Core\Environment::isComposerMode()) {
        $pharFileName = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath($extKey)
                        . 'Libraries/phpoffice-phpspreadsheet.phar';
        if (is_file($pharFileName)) {
            @include 'phar://' . $pharFileName . '/vendor/autoload.php';
        }
    }
```

**Comment by franzholz** [comment]
Does this mean that all those formerly existing classes are contained in a compressed form inside of the file phpoffice-phpspreadsheet.phar? And the autoloader will be included in the file ext_localconf.php only if it is no composer installation?

**Comment by cjanody** [comment]
Yes.

**Comment by franzholz** [comment]
Do also edit the file ChangeLog with your name and email, a comment to this issue, and add "#2 and #4" to your comment there.

**Comment by cjanody** [comment]
ChangeLog updated
Resolve #3

**Pull request merged**
